<x-guest-layout>
    <div class="bg-gray-600 p-6">
        <div class="p-4 m-4 bg-white">




            <h1 class="text-lg m-3 font-bold">Privacy Policy</h1>
            <p class="text-sm m-1 p-2 ">Last updated: February 06, 2021</p>

            <p class="text-sm m-1 p-2 ">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

            <p class="text-sm m-1 p-2 ">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
            created with the help of the Privacy Policy Generator.</p>

            <h1 class="text-lg m-3 font-bold">Interpretation and Definitions</h1>
            <h3 class="text-base m-2 font-bold">Interpretation</h3>
            <p class="text-sm m-1 p-2 ">The words of which the initial letter is capitalized have meanings defined under the following conditions.</p>
            <p class="text-sm m-1 p-2 ">The following definitions shall have the same meaning regardless of whether they appear in singular or in
            plural.</p>

           <h3 class="text-base m-2 font-bold"> Definitions</h3>
            <p class="font-bold">For the purposes of this Privacy Policy:</p>

            <p class="text-sm m-1 p-2 "><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</p>

            <p class="text-sm m-1 p-2 "><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to mola.</p>

            <p class="text-sm m-1 p-2 "><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website,
            containing the details of Your browsing history on that website among its many uses.</p>

            <p class="text-sm m-1 p-2 "><b>Country</b> refers to: Spain</p>

            <p class="text-sm m-1 p-2 "><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>

            <p class="text-sm m-1 p-2 "><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</p>

            <p class="text-sm m-1 p-2 "><b>Service</b> refers to the Website.</p>

            <p class="text-sm m-1 p-2 "><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It
            refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide
            the Service on behalf of the Company, to perform services related to the Service or to assist the Company in
            analyzing how the Service is used.</p>

            <p class="text-sm m-1 p-2 "><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User
            can log in or create an account to use the Service.</p>

            <p class="text-sm m-1 p-2 "><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the
            Service infrastructure itself (for example, the duration of a page visit).</p>

            <p class="text-sm m-1 p-2 "><b>Website</b> refers to {{config('app.name')}}, accessible from {{config('app.url')}}</p>

            <p class="text-sm m-1 p-2 "><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of
            which such individual is accessing or using the Service, as applicable.</p>

            <h1 class="text-lg m-3 font-bold">Collecting and Using Your Personal Data</h1>
            <h3 class="text-base m-2 font-bold">Types of Data Collected</h3>
            <p class="font-bold">Personal Data</p>
            <p class="text-sm m-1 p-2 ">While using Our Service, We may ask You to provide Us with certain personally identifiable information that
            can be used to contact or identify You. Personally identifiable information may include, but is not limited
            to:</p>
            <ul class="p-2">
            <li class="p-2">-Email address</li>

            <li class="p-2">-First name and last name</li>
            </ul>
            <h3 class="text-base m-2 font-bold">Usage Data</h3>

            <p class="text-sm m-1 p-2 ">Usage Data is collected automatically when using the Service.</p>

            <p class="text-sm m-1 p-2 ">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
            browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the
            time spent on those pages, unique device identifiers and other diagnostic data.</p>

            <p class="text-sm m-1 p-2 ">When You access the Service by or through a mobile device, We may collect certain information automatically,
            including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP
            address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.</p>

            <p class="text-sm m-1 p-2 ">We may also collect information that Your browser sends whenever You visit our Service or when You access
            the Service by or through a mobile device.</p>

            <h1 class="font-bold">Tracking Technologies and Cookies</h1>
            <p class="text-sm m-1 p-2 ">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
            information. Tracking technologies used are beacons, tags, and scripts to collect and track information and
            to improve and analyze Our Service. The technologies We use may include:</p>
            <ul class="p-2">
           <li class="p-2">-<b> Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your browser to
            refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You
            may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it
            will refuse Cookies, our Service may use Cookies.</li>
           <li class="p-2">-<b> Flash Cookies.</b> Certain features of our Service may use local stored objects (or Flash Cookies) to collect
            and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed
            by the same browser settings as those used for Browser Cookies. For more information on how You can delete
            Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared
            objects?" available at
            <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"> Here</a></li>
            <li class="p-2">-<b>Web Beacons.</b> Certain sections of our Service and our emails may contain small electronic files known as web
            beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for
            example, to count users who have visited those pages or opened an email and for other related website
            statistics (for example, recording the popularity of a certain section and verifying system and server
            integrity).</li>
            </ul>
            <p class="text-sm m-1 p-2 ">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
            mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
            Learn more about cookies: Cookies: What Do They Do?.</p>

            <p class="text-sm m-1 p-2 ">We use both Session and Persistent Cookies for the purposes set out below:</p>
            <table class="table-fixed text-center border border-gra">
                <thead class="bg-green-400 text-gray-600">
                    <tr>
                        <th class="w-1/6 py-4 ">Name</th>
                        <th class="w-1/6">Type</th>
                        <th class="w-1/6">Administred by</th>
                        <th class="w-3/6">Purpose</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Necessary / Essential Cookies</td>
                        <td>Session Cookies</td>
                        <td>Us</td>
                        <td> These Cookies are essential to provide You with services available through the Website and to
                            enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user
                            accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use
                            these Cookies to provide You with those services.</td>
                    </tr>
                    <tr>
                        <td>Cookies Policy / Notice Acceptance Cookies</td>
                        <td>Persistent Cookies</td>
                        <td>Us</td>
                        <td>These Cookies allow us to remember choices You make when You use the Website, such as remembering
                            your login details or language preference. The purpose of these Cookies is to provide You with a more
                            personal experience and to avoid You having to re-enter your preferences every time You use the Website.</td>
                    </tr>
                </tbody>
            </table>

            <h3 class="text-base m-2 font-bold">Use of Your Personal Data</h3>
            <p class="text-sm m-1 p-2 ">{{config('app.name')}} may use Personal Data for the following purposes:</p>
            <ul class="p-2">
            <li class="p-2">-To provide and maintain our Service, including to monitor the usage of our Service.</li>

            <li class="p-2">-To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide
            can give You access to different functionalities of the Service that are available to You as a registered
            user.</li>

            <li class="p-2">-To manage Your requests: To attend and manage Your requests to Us.</li>

            </ul>

            <h3 class="text-base m-2 font-bold">We may share Your personal information in the following situations:</h3>

            <p class="text-sm m-1 p-2 "><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze
            the use of our Service, to contact You.</p>

            <p class="text-sm m-1 p-2 "><b>With Your consent:</b> We may disclose Your personal information for any other purpose with Your consent.</p>
            <h3 class="text-base m-2 font-bold">Retention of Your Personal Data</h3>
            <p class="text-sm m-1 p-2 ">{{config('app.name')}} will retain Your Personal Data only for as long as is necessary for the purposes set out in this
            Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
            obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
            disputes, and enforce our legal agreements and policies.</p>

            <p class="text-sm m-1 p-2 ">{{config('app.name')}}will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for
            a shorter period of time, except when this data is used to strengthen the security or to improve the
            functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

            <h3 class="text-base m-2 font-bold">Transfer of Your Personal Data</h3>
            <p class="text-sm m-1 p-2 ">Your information, including Personal Data, is processed at the Company's operating offices and in any other
            places where the parties involved in the processing are located. It means that this information may be
            transferred to — and maintained on — computers located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>

            <p class="text-sm m-1 p-2 ">Your consent to this Privacy Policy followed by Your submission of such information represents Your
            agreement to that transfer.</p>

            <p class="text-sm m-1 p-2 ">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization
            or a country unless there are adequate controls in place including the security of Your data and other
            personal information.</p>

            <h1 class="text-lg m-3 font-bold">Disclosure of Your Personal Data</h1>


            <h3 class="text-base m-2 font-bold">Law enforcement</h3>
            <p class="text-sm m-1 p-2 ">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
            by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

            <h3 class="text-base m-2 font-bold">Other legal requirements</h3>
            <p class="text-sm m-1 p-2 ">{{config('app.name')}} may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

            <p class="text-sm m-1 p-2 ">Comply with a legal obligation</p>
            <p class="text-sm m-1 p-2 ">Protect and defend the rights or property of the Company</p>
            <p class="text-sm m-1 p-2 ">Prevent or investigate possible wrongdoing in connection with the Service</p>
                <p class="text-sm m-1 p-2 ">Protect the personal safety of Users of the Service or the public</p>
                    <p class="text-sm m-1 p-2 ">Protect against legal liability</p>
                        <h3 class="text-base m-2 font-bold">Security of Your Personal Data</h3>
                            <p class="text-sm m-1 p-2 ">The security of Your Personal Data is important to Us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable
            means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            <h3 class="text-base m-2 font-bold">Children's Privacy</h3>
            <p class="text-sm m-1 p-2 ">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
            information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your
            child has provided Us with Personal Data, please contact Us. If We become aware that We have collected
            Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to
            remove that information from Our servers.</p>

            <p class="text-sm m-1 p-2 ">If We need to rely on consent as a legal basis for processing Your information and Your country requires
            consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

            <h3 class="text-base m-2 font-bold">Links to Other Websites</h3>
            <p class="text-sm m-1 p-2 ">Our Service may contain links to other websites that are not operated by Us. If You click on a third party
            link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
            of every site You visit.</p>

            <p class="text-sm m-1 p-2 ">We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.</p>

            <h3 class="text-base m-2 font-bold">Changes to this Privacy Policy</h3>
            <p class="text-sm m-1 p-2 ">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page.</p>


            <h3 class="text-base m-2 font-bold">Contact Us</h3>
            <p class="text-sm m-1 p-2 ">If you have any questions about this Privacy Policy, You can <a href="{{route('contact')}}"> contact us</a></p>

        </div>
    </div>
</x-guest-layout>
